### ISSUE TITLE
Consider Sequence Support?

### ISSUE THREAD

**Issue by rainydew** [smarie/python-yamlable#12]
```python
# coding: utf-8
from yamlable import YamlObject2
import yaml

class Base:
    def __init__(self, *args, **kwargs):
        print("here", args, kwargs)
        self.args = args
        self.kwargs = kwargs

    def __repr__(self):
        return f"{self.__dict__}"


class Ice(YamlObject2, Base):
    yaml_tag = "![*ice]"


class Fire(YamlObject2, Base):
    yaml_tag = "![*fire]"


file = """
dict:
  - &ice ~
  - &fire ~
data:
  - ![*ice] {k: 1, v: 2}
  - ![*fire] [1, 2]
"""

data = yaml.safe_load(file)

print(data)
```

When parsing Ice (mapping, to dict), everything works well. However YamlAble doesn't have a handler to handle sequence yet, it will cause
`
E:\Python36\python.exe C:/Users/Administrator/AppData/Roaming/JetBrains/PyCharm2020.1/scratches/test_scratch.py
here () {'k': 1, 'v': 2}

Traceback (most recent call last):
  File "C:/Users/Administrator/AppData/Roaming/JetBrains/PyCharm2020.1/scratches/test_scratch.py", line 31, in <module>
    data = yaml.safe_load(file)
  File "E:\Python36\lib\site-packages\yaml\__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "E:\Python36\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "E:\Python36\lib\site-packages\yaml\constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "E:\Python36\lib\site-packages\yaml\constructor.py", line 60, in construct_document
    for dummy in generator:
  File "E:\Python36\lib\site-packages\yaml\constructor.py", line 408, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "E:\Python36\lib\site-packages\yaml\constructor.py", line 130, in construct_sequence
    for child in node.value]
  File "E:\Python36\lib\site-packages\yaml\constructor.py", line 130, in <listcomp>
    for child in node.value]
  File "E:\Python36\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "E:\Python36\lib\site-packages\yamlable\yaml_objects.py", line 115, in from_yaml
    constructor_args = read_yaml_node_as_dict(loader, node)
  File "E:\Python36\lib\site-packages\yamlable\base.py", line 210, in read_yaml_node_as_dict
    loader.flatten_mapping(node)
  File "E:\Python36\lib\site-packages\yaml\constructor.py", line 184, in flatten_mapping
    key_node, value_node = node.value[index]
TypeError: 'ScalarNode' object is not iterable
`

Maybe a type router to call constructor in different ways is better?

**Comment by smarie** [comment]
Thanks  @rainydew  ! Before going further on how to improve `yamlable`, would you know if/how `pyyaml.YAMLObject` handles this ? If reading objects from sequences is confirmed to be a valid scenario, we can definitely improve the lib (I would be happy to review a PR if you wish to give a try).

**Comment by smarie** [comment]
I just had a look, `pyyaml` does not support it:

```python
import yaml

class Hero:
    def __init__(self, name, hp, sp):
        self.name = name
        self.hp = hp
        self.sp = sp

    def __repr__(self):
        return "%s(name=%r, hp=%r, sp=%r)" % (self.__class__.__name__, self.name, self.hp, self.sp)

yaml.load("""
!!python/object:__main__.Hero
- Welthyr Syxgon
- 1200
- 0
""")
```

fails with 

```
yaml.constructor.ConstructorError: expected a mapping node, but found sequence
  in "<unicode string>", line 2, column 1:
    !!python/object:__main__.Hero
```

**Comment by smarie** [comment]
Same with scalar:

```
yaml.load("""
!!python/object:__main__.Hero
Welthyr Syxgon
""")
```

**Comment by smarie** [comment]
Hi @rainydew it should now be available in yamlable version 1.1.0
I took this opportunity also to improve the examples using mkdocs-gallery. Let me know what you think ! ;)

**Comment by rainydew** [comment]
hi @smarie sorry quite busy recently, thanks a lot for improving and i will try soon~

**Comment by rainydew** [comment]
hi @smarie  thanks it works wonderful and can do lots of work with python IDE like pycharm... (for tag hint and auto complete it can make lots of function and be very flexible, can use as DSL)

**Comment by smarie** [comment]
Super cool ! Thanks @rainydew for the feedback
